### PR TITLE
Highlight exceptions

### LINKED ISSUE #3994: highlights also needs an exclude list
Currently it is impossible to silence specific notifications that include your nick because there are no negative-highlight-matches.

We need a list of words to be excluded from notifications that passed the current include list, so we remove the false positives.

Imagine that you have bots that may notify about build status or commit messages made by yourself, and you are high-likely to not want to be notified about your own actions.

### PR DESCRIPTION
**Pull request by Jay2k1**
This adds an exception/exclude list for strings that should _not_ trigger highlights. The code strips IRC formatting before testing messages for the exceptions, so that the given strings match colored/styled messages as well. Fixes #3994.

I basically duplicated the highlight code and reversed it.

Both custom highlight settings fields now have labels and help text:

image

### CODE REVIEW

File: src/client.js [hunk 1]
```diff
@@ -447,6 +449,34 @@ Client.prototype.compileCustomHighlights = function () {
 	);
 };
 
+Client.prototype.compileCustomHighlightExceptions = function () {
```
Comment (xPaw) [inline src/client.js:452]: Would be nice to have a single function so it doesn't duplicate all the code. You can pass `client.config.clientSettings.highlightExceptions` into it, and make it return null or the compiled regex.

File: src/plugins/irc-events/message.js [hunk 2]
```diff
@@ -126,6 +126,14 @@ module.exports = function (irc, network) {
 			}
 		}
 
+		// if highlight exceptions match, do not highlight at all
```
Comment (xPaw) [inline src/plugins/irc-events/message.js:129]: This comment should be below, where the `if` is.

As for `cleanMessage`, should we make `client.highlightRegex` also test against it?

File: client/components/Windows/Settings.vue [hunk 3]
```diff
@@ -351,16 +351,45 @@ This may break orientation if your browser does not support that."
...
+				</label>
+			</div>
+
+			<div v-if="!$store.state.serverConfiguration.public && $store.state.settings.advanced">
+				<label class="opt">
+					<label for="highlightExceptions" class="opt">
+						Highlight exceptions
+						<span
+							class="tooltipped tooltipped-n tooltipped-no-delay"
+							aria-label="If a message contains any of these comma-separated expressions, it will not trigger a highlight
```
Comment (xPaw) [inline client/components/Windows/Settings.vue:380]: This probably needs new lines as it will overflow (and css tooltips are kinda terrible)

**Comment by xPaw** [comment]
cc @ssbarnea to give this a test.

File: client/components/Windows/Settings.vue (hunk 3 above)
Comment (Jay2k1) [reply client/components/Windows/Settings.vue:380]: Yeah, where you said I should add a line break, can't that tooltip get a max-width or something so we don't have to care about inserting line breaks?

File: client/components/Windows/Settings.vue [hunk 4]
```diff
@@ -351,16 +351,45 @@ This may break orientation if your browser does not support that."
...
+						</span>
 					</label>
 					<input
 						id="highlights"
 						:value="$store.state.settings.highlights"
 						type="text"
 						name="highlights"
 						class="input"
-						placeholder="Custom highlights (comma-separated keywords)"
+						placeholder="word, some more words, anotherword"
```
Comment (xPaw) [inline client/components/Windows/Settings.vue:369]: Shall we keep comma-separated here to make it clearer?

Like `Comma-separated, for example: word, some more words, anotherword` or something.

Comment (Jay2k1) [reply client/components/Windows/Settings.vue:369]: Maybe. We can use "e.g." so the text fits the field size:
image

File: src/plugins/irc-events/message.js (hunk 2 above)
Comment (Jay2k1) [reply src/plugins/irc-events/message.js:129]: > As for cleanMessage, should we make client.highlightRegex also test against it?
Actually, why not. Things like inserting a control character into nicknames in bot messages will not affect this, and if you specifically add things to custom highlights, you probably prefer if that highlights regardless of formatting.

File: test/tests/customhighlights.js [hunk 5]
```diff
@@ -96,4 +96,56 @@ describe("Custom highlights", function () {
 		client.compileCustomHighlights();
 		expect(client.highlightRegex).to.be.null;
 	});
+
+	// tests for highlight exceptions
+	client.config.clientSettings.highlights = "foo, @all,   sp ace   , 고";
+	client.config.clientSettings.highlightExceptions = "foo bar, bar @all, test sp ace test";
```
Comment (xPaw) [inline test/tests/customhighlights.js:102]: You set these but don't call `compileCustomHighlights`?

File: test/tests/customhighlights.js [hunk 6]
```diff
@@ -96,4 +96,56 @@ describe("Custom highlights", function () {
...
+
+	it("should NOT highlight due to highlight exceptions", function () {
```
Comment (xPaw) [inline test/tests/customhighlights.js:104]: this `NOT` should be in next test i think?

File: test/tests/customhighlights.js (hunk 5 above)
Comment (Jay2k1) [reply test/tests/customhighlights.js:102]: Oh, I forgot to add that, yes. The custom highlights are cleared in line 91 and 95, so I need to recompile anyway.

File: test/tests/customhighlights.js (hunk 6 above)
Comment (Jay2k1) [reply test/tests/customhighlights.js:104]: No, it's not the regex where the negation happens but the code, so the regex needs to match things that actually should not highlight and vice versa.
Or in other words, if this test fails, the user would get a highlight because the exception code fails.

**Comment by xPaw** [comment]
Can you rebase please, I will merge it.
