### PR TITLE
Display a broken link icon and red text color when not joined on a channel

### LINKED ISSUE #3080: Add styling for parted channels
They have a class, just need to add actual styling for it.

Change icon? Make them faded or italic?

### PR DESCRIPTION
**Pull request by astorije**
Closes #3080.

screen shot 2019-02-25 at 00 21 59

### CODE REVIEW

File: client/components/Channel.vue [hunk 1]
```diff
@@ -9,6 +9,11 @@
 			:class="{ highlight: channel.highlight }"
 			class="badge">{{ channel.unread | roundBadgeNumber }}</span>
 		<template v-if="channel.type === 'channel'">
+			<span
```
Comment (xPaw) [inline client/components/Channel.vue]: Hide this with v-if

Comment (astorije) [reply client/components/Channel.vue]: I did a thing, can you check if that's what you meant? 🙏

Comment (xPaw) [reply client/components/Channel.vue]: Yep. We'll want to do this with other icons too (the ones you moved styles for).
