### PR TITLE
Fix Alt+Up/Down cycling through channels of collapsed networks

### LINKED ISSUE #2200: Alt+Up/Down should not cycle through channels of a collapsed network

### PR DESCRIPTION
**Pull request by Raqbit**
This Fixes #2200.
It now filters channels inside a collapsed network when cycling through channels.

### CODE REVIEW

File: client/js/keybinds.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ Mousetrap.bind([
 	"alt+up",
 	"alt+down",
 ], function(e, keys) {
-	const channels = sidebar.find(".chan");
+	const channels = sidebar.find(".chan").not(".network.collapsed .channel");
```
Comment (xPaw) [inline client/js/keybinds.js]: This still allows queries and other windows to be targeted. This needs to target `:not(.lobby)` or something like that.

**Comment by MaxLeiter** [comment]
@astorije, based on xPaw's last comment, I think queries will still be targeted.

**Comment by xPaw** [comment]
Yeah I just tested it, and I can still iterate through hidden channels and queries. So it's not fixed.
